# Generated by Django 3.2.5 on 2021-07-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_livros', '0003_alter_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
