# Generated by Django 3.2.5 on 2021-07-21 06:14

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_livros', '0004_livro_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_lancamento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='empresa_publicadora',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='livro',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Ativo'), ('2', 'Não Ativo')], default='Ativo', max_length=6),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=isbn_field.fields.ISBNField(blank=True, clean_isbn=False, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
    ]
