# Generated by Django 3.2.5 on 2021-07-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_livros', '0005_auto_20210721_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='paginas',
            field=models.CharField(max_length=6),
        ),
    ]
