# Generated by Django 3.2.5 on 2021-07-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_livros', '0006_alter_livro_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='paginas',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
