# Generated by Django 3.2.5 on 2021-07-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_livros', '0007_alter_livro_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
