# Generated by Django 3.2.5 on 2021-07-21 08:49

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_livros', '0008_livro_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(null=True, upload_to='capas'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='empresa_publicadora',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='livro',
            name='estado',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Não Ativo')], default='Ativo', max_length=6),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=isbn_field.fields.ISBNField(clean_isbn=False, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs'),
        ),
    ]
