# Generated by Django 3.2.5 on 2021-07-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_livros', '0009_auto_20210721_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_de_lancamento',
            field=models.DateField(),
        ),
    ]
